kind: pipeline
name: project1
pipeline:
    project1-build:
      image: docker:18.09-dind
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        # - DOCKER_HOST=tcp://docker:2375
      commands:
        - docker ps
        - echo "Hello"
        - docker build -t project1 project1
    