kind: pipeline
name: default
pipeline:
    project2-build:
      image: docker:18.09-dind
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        # - DOCKER_HOST=tcp://docker:2375
      commands:
        - docker ps
        - echo "world!"
        - docker build -t project2 project2
    